# Generated by Django 3.2.23 on 2025-06-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedRoute',
        ),
        migrations.DeleteModel(
            name='FuelStation',
        ),
    ]
