# Generated by Django 3.2.23 on 2025-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fuelstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
